---
- hosts: localhost
#  become: yes
  gather_facts: false
  tasks:
    - name: installing wget 
      apt:
        name: wget
        state: present 
    - name: download Jenkins
      get_url:
        url: https://updates.jenkins-ci.org/download/war/2.248/jenkins.war
        dest: /home/elaig
    
- hosts: dev
#  become: yes
  gather_facts: false
  tasks:
    - name: copy jenkins war to host machines
      copy:
        src: /home/elaig/jenkins.war
        dest: /home/elaig/jenkins.war
    - name: creating folder structure and running jenkins in the background 
      shell: |
        mkdir /home/elaig/jenkins
        mv /home/elaig/jenkins.war /home/elaig/jenkins
        nohup java -jar /home/elaig/jenkins/jenkins.war &
